baseURL = "http://localhost:1313"
locale = "en-us"
title = "A minimal Hugo website"
theme = "zettmin"

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "/about/"
  weight = 2

  [[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 3

  [[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 4

  [[menu.main]]
  name = "Subscribe"
  url = "/index.xml"

[markup]
  [markup.highlight]
  codeFences = true

[params]
  footer = "&copy; [lomarco](https://github.com/lomarco) {Year}"
